### ISSUE TITLE
Any plans to update iOS to support AFNetworking v2.x?

### ISSUE THREAD

**Issue by gaharrington** [abbyysdk/ocrsdk.com#29]
The iOS example uses:  pod "OCRSDKClient", "0.2.1"

That pod uses AFNetworking v1.3.

Do you have any plans to update that to support AFNetworking v2.x?

**Comment by Dmitry-Me** [comment]
No, and since we have an iOS sample that doesn't use AFNetworking we've decided to remove the AFNetworking sample.
