### ISSUE TITLE
Abbyy.Ocrsdk.client in JAVA

### ISSUE THREAD

**Issue by gopisankar11** [abbyysdk/ocrsdk.com#35]
args.length  is zero how to add parameter in args in TestApp class
Vector<String> argList  is also null pointer exception 

Implement your project in eclipse for java. implement completion...Please Explain  run test app

**Comment by Dmitry-Me** [comment]
You should pass parameters on the command line.

**Comment by gopisankar11** [comment]
ok thank you for reply...

**Comment by gopisankar11** [comment]
ok buddy thanks.....
