### ISSUE TITLE
from file doesnt work

### ISSUE THREAD

**Issue by wissenandroid** [abbyysdk/ocrsdk.com#38]
i m using abby's code sample for android. i clicked the "from camera" button. its working fine. But i clicked "from file",i choose the image but then nothing happens just shows activity result.

i solved my problem. but now i have a new problem. this is the first problem solution

go to MainActivty.java and change

Cursor cur = managedQuery(imageUri, projection, null, null, null);//(imageUri return null, lolipop issues i think)

to

Cursor cur = getContentResolver().query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, projection, null, null, null);

my second problem is ; my photo uploading correctly but response return empty. i can't find the problem please yours android developer can see this problem

**Comment by Dmitry-Me** [comment]
Your issue doesn't specify which version of Android you use, how you run this code, whether you've ensured that you've set the credentials properly. Without those it's impossible to start working on this.

**Comment by wissenandroid** [comment]
i solved the problem
http://forum.ocrsdk.com/questions/5255/cloud-ocr-sdk-from-file
