### ISSUE TITLE
Trying to incorporate multiple languages 

### ISSUE THREAD

**Issue by steveandrewwong** [abbyysdk/ocrsdk.com#39]
I am trying to transfer code from ProcessingParams to a URLViewController that I created to allow users to select different language libraries and output format through UIbuttons. 

However when I created these codes into viewcontroller, it throws out error about invalid parameter of taskID. Wondering how I should change the parameters?

OcrSdkDemo[4003:1654971] *** Assertion failure in -[Client uploadFinished:], /Users/SteveAndrewWong/Desktop/OcrSdkDemo copy 2/Sources/Client.m:111
2015-12-26 18:28:11.633 OcrSdkDemo[4003:1654971] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: task.ID'

- (NSString*)urlString
{
	return @"language=(language)&exportFormat=(outputformat)";
}

<img width="1020" alt="screen shot 2015-12-19 at 6 05 27 pm" src="https://cloud.githubusercontent.com/assets/8135740/12006055/b6e95cde-abff-11e5-8079-1e922984672b.png">

**Comment by Dmitry-Me** [comment]
How could one reproduce the problem you observe?
