### ISSUE TITLE
Code must run on server side under node js

### ISSUE THREAD

**Issue by numairali** [abbyysdk/ocrsdk.com#44]
Hi,

I need to work with javascript code provided and I am facing difficulties in using the javascript code.

Can anyone please guide me how I can work with this piece of code.

I already execute the command "npm install xml2js" 

I shall be vary thankful for the kind help.

Thanks

**Comment by Dmitry-Me** [comment]
Install NodeJS, then invoke `node test.js` on command line.

**Comment by numairali** [comment]
I have done that but same error is coming up.
![capture](https://cloud.githubusercontent.com/assets/18556088/14649887/50ebcfee-0626-11e6-8ef3-fc34883966d4.PNG)

**Comment by Dmitry-Me** [comment]
This is weird. What does `console.log()` output if you ask it to output `process.argv[0]`?

**Comment by numairali** [comment]
Do I have to do any configurations before using that code? or any server that needs to be created?

I have never worked on Node.js.

Please help.

**Comment by Dmitry-Me** [comment]
This code should just work. What does `console.log(process.argv[0])` output?

**Comment by numairali** [comment]
![capture](https://cloud.githubusercontent.com/assets/18556088/14654492/34138c08-063b-11e6-8192-bfddc6392dac.PNG)

Please have a look

**Comment by Dmitry-Me** [comment]
Interesting. Which version of Windows is this happening on?

**Comment by numairali** [comment]
Windows 10 Pro 64bit

**Comment by Dmitry-Me** [comment]
Clearly this is not the documented behavior. NodeJS documentation says https://nodejs.org/api/process.html#process_process_argv the first element should be `node`. Looks like a bug in NodeJS implementation.

**Comment by numairali** [comment]
Is there any solution for that ?

**Comment by Dmitry-Me** [comment]
Yeap, file a bug against NodeJS with a minimal piece of code to reproduce the problem.

**Comment by Dmitry-Me** [comment]
There was a change in NodeJS a while ago and the documentation was not proper updated yet. This is a defect report in NodeJS repo https://github.com/nodejs/node/issues/7434 This change https://github.com/abbyysdk/ocrsdk.com/commit/b9d52c804ff8c92e6934f1b557249e330e56f8db adapts the sample to new behavior.
