### ISSUE TITLE
bug in ocrsdk.js

### ISSUE THREAD

**Issue by michaelbadichi** [abbyysdk/ocrsdk.com#50]
on line 292
        result += '?' + this.customOptions;
should be:
        result += '&' + this.customOptions;

also, i think its better to have customOption an object of key/value and not have the user of the library aware of the URLish nature of the fields. (so user does not need to know to add & for multiple custom options).

**Comment by Dmitry-Me** [comment]
Resolved with https://github.com/abbyysdk/ocrsdk.com/commit/757fba153c3e43d0ac9ae7ee6328b697b77013c0 Thank you for reporting this.
