### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: task.downloadURL'

### ISSUE THREAD

**Issue by youquanli** [abbyysdk/ocrsdk.com#53]
Happy new year, everyone!
I thank the team for providing this iOS sample project.
I tried to run the project and recognize the sample image in the app.
But I got the following error:

2017-01-06 19:01:01.027 OcrSdkDemo[9668:1150661] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: task.downloadURL'

So I debugged the project, and found that task.downloadURL is null at runtime.
The following is the code snippet where task.downloadURL is null.
The code snippet is in the Client.m file.

- (void)processingFinished:(HTTPOperation*)operation
{
	if (operation.error != nil) {
		if ([self.delegate respondsToSelector:@selector(client:didFailedWithError:)]) {
			[self.delegate client:self didFailedWithError:operation.error];
		}
	} else {
		Task* task = [[Task alloc] initWithData:operation.receivedData];
		
		if ([self.delegate respondsToSelector:@selector(clientDidFinishProcessing:)]) {
			[self.delegate clientDidFinishProcessing:self];
		}
        
		NSParameterAssert(task);
		NSParameterAssert(task.downloadURL);

Is there anything I missed? I replaced the app id and password.

I should be grateful if you could help me fix this issue as soon as possible.
Thank you for your time and help.

**Comment by Dmitry-Me** [comment]
It looks like task processing failed and its state is not `Completed` but perhaps `ProcessingFailed` or some other state. If this happens then `didStartElement` in `Task.m` doesn't set `downloadURL` because there's nothing to set. The code you cite doesn't handle this case properly. The right behavior would be to check `task.status` and proceed depending on its value.

**Comment by youquanli** [comment]
Hi, Dmitry
Thank you very much for your reply.
You are right. The task processing failed because the app ID I used had no balance.
So I used another app ID with some balance pages, and your code works very well.

By the way do you happen to know if ABBYY Cloud SDK supports OCR of handwritten documents as well?
I really appreciate your help, and wish you best of luck in the new year.
Thank you.

**Comment by youquanli** [comment]
Hi, Dmitry
Thank you very much for your reply.
You are right. The task processing failed because the app ID I used had no balance.
So I used another app ID with some balance pages, and your code works very well.

By the way do you happen to know if ABBYY Cloud SDK supports OCR of handwritten documents as well?
I really appreciate your help, and wish you best of luck in the new year.
Thank you.


________________________________

**Comment by Dmitry-Me** [comment]
It supports "handprinted" text - text written by hand one character at a time. http://ocrsdk.com/documentation/specifications/text-types/ "Handprinted" text is how various forms are filled in by hand - you have a grid and write one character per grid cell.

**Comment by youquanli** [comment]
Thank you for your quick consideration.
I'm trying to recognize images of handwritten text and I've tried with that option.
Unfortunately, it doesn't work so well, so I'm afraid I have to find another service.
Now I've been looking for a good one for over 2 weeks, but no luck.
I should be grateful if you could recommend one if any.
Thank you.

**Comment by Dmitry-Me** [comment]
What's you scenario? Do you have predefined forms with known layout?

**Comment by Dmitry-Me** [comment]
The issue with overly optimistic handling of finished tasks should have been fixed with this commit https://github.com/abbyysdk/ocrsdk.com/commit/e0fb87de3f2cfead5b30c7e6c58599b8ec5940bd

**Comment by youquanli** [comment]
I'm trying to recognize the following sample image, but I couldn't get result. Thanks.

![untitled1](https://cloud.githubusercontent.com/assets/20833260/21801271/e6cb5abe-d75b-11e6-9117-06fecd4f0da5.png)

**Comment by Dmitry-Me** [comment]
What's the problem exactly?

**Comment by youquanli** [comment]
I've uploaded the above image and got:
>0
  CD

**Comment by Dmitry-Me** [comment]
Which API method do you use to initiate processing?

**Comment by youquanli** [comment]
I tried with processImage and processTextField methods.

**Comment by Dmitry-Me** [comment]
`processTextField` should work. With this image the problem is most likely because of high amounts of noise and low image contrast.

**Comment by youquanli** [comment]
That's right. I think I have to do preprocessing.
Thank you for your help.

**Comment by Dmitry-Me** [comment]
If this is a photo then you could improve image quality greatly by using proper lighting.

**Comment by anilsutariya** [comment]
@Dmitry-Me  I am getting below error

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: task.ID'
