### ISSUE TITLE
Receipt Recognition Demo app: please allow Canada as receipt's country of origin

### ISSUE THREAD

**Issue by webmetender** [abbyysdk/ocrsdk.com#56]
Hi,

It is stated on ABBYY's website that Receipt Recognition is currenlty being beta tested for many countries, including Canada.

However, the Receipt Recognition Demo app does not allow to select Canada as the receipt country of origin.

I added "Canada" to the CountryOfOrigin enum: an error occurs "Invalid receipt country: Canada".

Could you please have a look at this?

Thank you :)

A.

**Comment by Dmitry-Me** [comment]
The necessary changes were deployed in the service. Enumeration values was also added in the sample: https://github.com/abbyysdk/ocrsdk.com/commit/a0c98997f3d19b1a3100d3a999e1e8cb7ccb5eb2
