### ISSUE TITLE
offline image processing.

### ISSUE THREAD

**Issue by TejaDroid** [abbyysdk/ocrsdk.com#82]
I have app, which has requirement of scan business card and convert it in contact, this sdk full fill my requirement but that not enough, we need scan business card offline as without having a internet, so will it possible with this sdk, if yes, then please let me know how?

Thanks.

**Comment by helen-os** [comment]
Hello! We suppose it could more convenient for you to use [FineReader Engine SDK](https://www.abbyy.com/ocr-sdk/) or [Mobile Capture SDK](https://www.abbyy.com/mobile-capture-sdk/). Please check the suitable solution with our sales team: [sales@abbyy.com](mailto:sales@abbyy.com).

**Comment by hisubbotin** [comment]
Reopen it if you have other questions.
