### ISSUE TITLE
XML:writeFormatting is not working

### ISSUE THREAD

**Issue by JrSurapaneni** [abbyysdk/ocrsdk.com#86]
I coded as follows 
ocr_engine = CloudOCR(application_id='', password='')
jpg = open('pic16.JPG', 'rb')
file = {jpg.name: jpg}
result = ocr_engine.process_and_download(file, exportFormat='xml&xml:writeFormatting=true', language='English')
result

for format, content in result.items():
    with open('converted.xml', 'wb') as output_file:
        output_file.write(content.read())
        output_file.close()

it threw the following Error:

HTTPError: 450 Client Error: Unknown format xmlwriteFormatting=true for url: http://cloud-eu.ocrsdk.com/processImage?exportFormat=xmlwriteFormatting%3Dtrue&language=English

**Comment by helen-os** [comment]
Hi! It seems that the request to Cloud OCR SDK server is not formed correctly: the processing URL should look like "http://cloud-eu.ocrsdk.com/processImage?exportFormat=xml&xml:writeFormatting=true&language=English". Please try to pass _xml:writeFormatting=true_ as a separate processing parameter or escape '&' symbol.

**Comment by JrSurapaneni** [comment]
Hi,
I've tried with escaping '&' symbol, same error popped up. how to pass xml:writeFormatting as separate Parameter

**Comment by JrSurapaneni** [comment]
Worked like a charm, thank you @helen-os .
